# MIT License, Copyright (c) 2023 Heiko Lübbe
# WordPress plugin zitat-service, see https://github.com/muhme/quote_wordpress
#
# docker-compose.yml - define and orchestrate the used docker containers

version: '3.5'
services:
    wordpress:
        container_name: quote_wp_wordpress
        build:
            context: .
            dockerfile: wordpress.Dockerfile
        restart: always
        environment:
            WORDPRESS_DB_HOST: mariadb
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DEBUG: 1
            WORDPRESS_CONFIG_EXTRA: define('FORCE_SSL_ADMIN', false);
        volumes:
            - ./plugin:/var/www/html/wp-content/plugins/zitat-service/
        ports:
            - "4080:80"
        depends_on:
            - mariadb
            - maildev
    mariadb:
        container_name: quote_wp_mariadb
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: wordpress
            MARIADB_USER: wordpress
            MARIADB_PASSWORD: wordpress
    phpmyadmin:
        container_name: quote_wp_phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "4081:80"
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - mariadb
    maildev:
        container_name: quote_wp_maildev
        image: maildev/maildev
        restart: always
        ports:
            - "4082:1080"
            - "1025:1025"
    playwright:
        container_name: quote_wp_playwright
        image: mcr.microsoft.com/playwright:v1.40.1  # Docker image version that matches local Playwright version
        restart: unless-stopped
        entrypoint: ["sleep", "31536000"] # don't use Playwright run, instead sleep one year
        volumes:
            - .:/quote_wordpress # to see HTML reports as file
        working_dir: /quote_wordpress
