# docker-compose.yml - Wordpress in docker with email
# hlu, Nov 26th 2023 - Nov 27th 2023
#
# MIT License, Copyright (c) 2023 Heiko Lübbe
# https://github.com/muhme/quote_wordpress

# $ docker compose up -d  
# $ docker exec -it quote_wp_wordpress bash

version: '3.5'
services:
    wordpress:
        container_name: quote_wp_wordpress
        build:
            context: .
            dockerfile: wordpress.Dockerfile
        restart: always
        environment:
            WORDPRESS_DB_HOST: mariadb
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DEBUG: 1
        ports:
            - "4080:80"
        # volumes:
        #  - ./wp:/var/www/html
        depends_on:
            - mariadb
            - maildev
    mariadb:
        container_name: quote_wp_mariadb
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: wordpress
            MARIADB_USER: wordpress
            MARIADB_PASSWORD: wordpress
    phpmyadmin:
        container_name: quote_wp_phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "4081:80"
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: root
        depends_on:
            - mariadb
    maildev:
        container_name: quote_wp_maildev
        image: maildev/maildev
        restart: always
        ports:
            - "4082:1080"
            - "1025:1025"
